### ISSUE TITLE
Error loading items

### ISSUE THREAD

**Issue by Blanka-boop** [strohne/Facepager#111] opened 2019-12-02 13:49 UTC
Hello!
Recently I downloaded the version 4.0.8 to fetch data from Youtube for student purposes, but every time I try to acces Facepager this message shows up, and I can't do anything in the app
![error](https://user-images.githubusercontent.com/58430324/69964564-5b670580-151b-11ea-85f6-78d3f5fb885e.png)
What should I do?

**Comment by strohne** [comment] 2019-12-02 14:54
Hi! 

Sounds like you have corrupted presets or api definitions. Those are located in the folder C:\Users\<your username>\Facepager. Could you try to delete the complete folder and then start Facepager? The default presets should be automatically downloaded at startup.

**Comment by strohne** [comment] 2019-12-18 19:12
I think I found the problem and updated some preset files, should work without reinstalling. (but will be definitely fixed in the next release)

**Closed by strohne** 2019-12-18 19:12 UTC

**Comment by MatthewLGibbons** [comment] 2020-07-31 02:38
![Facepager Presets problem](https://user-images.githubusercontent.com/36945742/88993527-540e2b00-d33a-11ea-8ef8-5e7d487baa8a.JPG)
The presets on Facepager 4.2 worked as expected the first day. But after restarting I got an 'Error downloading default presets' error, even after reinstalling Facepager. Do you have any suggestions? I can still download the default custom table columns, such as type. 


2020-07-31 14:20:36.837345 Error downloading default presets:HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /strohne/Facepager/master/presets/Generic-Scrape_Wikipedia_tables.3_10.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002BE2E607C50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')

**Comment by strohne** [comment] 2020-07-31 21:43
Hi, this error usually occurs if a) there is no stable  internet connection at startup or b) GitHub ist not available. 

Can you manually check whether https://raw.githubusercontent.com/strohne/Facepager/master/presets/Twitter-Get_list_of_followers.3_9.json is available and the start Facepager? Still getting errors?

**Comment by MatthewLGibbons** [comment] 2020-08-01 00:03
Hi Jakob,

It is working today at the university! I tried shutting down several times
yesterday, and we don't usually have trouble with the internet at the
university. But it looks as if doing something else was the right thing to
do.

 Thanks for replying so quickly. Matthew

I clicked on your link and got the below.


{
  "description": "Add user names as nodes (without the @). This preset
fetches you 10 pages with 100 followers each at maximum.\n\nEach user
has a numeric ID as well. In case you want to work with the numeric ID
change the parameter \"screen_name\" to \"user_id\". You can get the
user ID with the preset \"Get information about users\". Select the
result and fetch the data with this preset again.\n\nFor more
information see the reference:
https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-list.",
  "module": "Twitter",
  "speed": 200,
  "options": {
    "params": {
      "count": "100",
      "screen_name": "<Object ID>"
    },
    "basepath": "https://api.twitter.com/1.1",
    "resource": "/followers/list",
    "pages": 10
  },
  "columns": [
    "id",
    "name",
    "screen_name",
    "friends_count",
    "created_at",
    "errors.*.message"
  ],
  "name": "Get list of followers"
}

**Comment by strohne** [comment] 2020-08-01 11:27
Thanks for testing out. Once the presets are downloaded, usually everything should work even if the updates are not loaded. I think I will disable automatic updates in future versions since GitHub sometimes has problems delivering the files.

**Comment by JonasBjerg** [comment] 2020-11-17 10:01
![image](https://user-images.githubusercontent.com/69581157/99375418-00612680-28c4-11eb-9854-971419abf2bd.png)

Hi I get a similar but different error, and I have tried it on multiple different networks now. I have also tried deleting the FacePager folder and reinstalling the .exe

I believe there is something wrong with my SSL certificate, but i do not know what, please help

**Comment by strohne** [comment] 2020-11-17 11:49
Hi! I think this is a different issue, moved your comment to a new issue.
