### ISSUE TITLE
Facepager V3.8 getting Query Status error (400) when fetching data in FB...

### ISSUE THREAD

**Issue by crockycmb** [strohne/Facepager#65] opened 2017-06-23 20:43 UTC
I'm definitely just learning this FacePager altogether, and getting this error every time I fetch any Resource type...  Attached is the screen shot trying all type of resource getting the sme "error 400." 

![image](https://user-images.githubusercontent.com/29664311/27499715-1134c40e-5833-11e7-836c-196bbbb4a799.png)

**Comment by strohne** [comment] 2017-06-24 18:22
Pls provide details about the error message, see offcut node.

btw: the default setting of the base path is outdated, maybe you could change it to version 2.3

**Comment by strohne** [comment] 2017-07-03 21:09
Looks like you try to access the feed of a group. This is not possible without being admin of the group.

**Comment by crockycmb** [comment] 2017-07-16 11:31
Error message expanded, onoffcut node.
The default setting of the base path is changed to version 2.3
I'm admin of the group queried.

![image](https://user-images.githubusercontent.com/29664311/28247122-6f5689d8-69f8-11e7-91df-309b6f2dd09d.png)

**Comment by strohne** [comment] 2017-07-16 14:29
And what is the error message?

**Comment by crockycmb** [comment] 2017-07-16 20:57
Mr. Strohne,  I ran this same request from Facebook graph API and it seems to get me the results I was expecting...  I'm not really sure how to expand the troubleshooting or the error message I need to explore in the FacePager...  Your guidance is deeply appreciated...  

![image](https://user-images.githubusercontent.com/29664311/28251272-c7457a88-6a47-11e7-8cc1-718b8fb6eb41.png)

**Comment by strohne** [comment] 2017-07-17 08:32
Ok. let's try...

1. Expand the node in the detail view (right top pane), look at the error message and report back.

2. To get details about permissions pls read the Facebook Graph API reference, particularly https://developers.facebook.com/docs/graph-api/reference/v2.9/group (follow the links in the edges section as well) Maybe some things are not permitted if you are not the developer of the app. In this case you need to register your own app (see https://github.com/strohne/Facepager/blob/master/src/credentials.py.readme)

3. To run the exact same query like in your screenshot in Facepager you need to
    * add the node `me`
    * set the version in base path to 2.9: `https://graph.facebook.com/v2.9/`
    * set the resource  to `<Object ID>/groups`
    * set the parameter `fields` to `id,name,members`
    * after fetching data check the status log: is it really the same request?

**Comment by crockycmb** [comment] 2017-07-18 12:18
This is the results when I run the following http calls..

 https://graph.facebook.com/v2.9/me/groups?id%2Cname%2Cmembers=&limit=100&access_token=EAABj9aBk8VwBAIGSyjZBwZC8xiw8dHVYO2bKPXkcqrKSjpBh6j3WKaaV5O3Ytv87yocYn3c57vi1Sveg90x0wxIECMDqFE2PNWHl85AZC8AZBA9Te4PZBxwm79mfZCLZANEx0K00yax3eDZAlYDTylZABYwBdZAKJinMDSsw1d4yGnyTzkQZDZD

Result:

{
   "data": [
      
   ]
}

------

https://graph.facebook.com/v2.9/638868926134801/groups?id%2Cname%2Cmembers=&limit=100&access_token=EAABj9aBk8VwBAIGSyjZBwZC8xiw8dHVYO2bKPXkcqrKSjpBh6j3WKaaV5O3Ytv87yocYn3c57vi1Sveg90x0wxIECMDqFE2PNWHl85AZC8AZBA9Te4PZBxwm79mfZCLZANEx0K00yax3eDZAlYDTylZABYwBdZAKJinMDSsw1d4yGnyTzkQZDZD

Result:

{
   "error": {
      "message": "Unsupported get request. Object with ID '638868926134801' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "A5NmFEb5FTd"
   }
}

![image](https://user-images.githubusercontent.com/29664311/28316535-3f9f7e1c-6b91-11e7-8fb8-d7de1e88b642.png)

**Comment by strohne** [comment] 2017-07-18 16:01
These are different requests, check the fields-parameter.

By the way: this is not a Facepager issue. The problem is about working with the Facebook Graph API. I will close the issue now. Pls get familiar with the API.

**Closed by strohne** 2017-07-18 16:01 UTC
