### ISSUE TITLE
Log in problem with facebook

### ISSUE THREAD

**Issue by Talha1721** [strohne/Facepager#136] opened 2020-08-08 14:54 UTC
Hello, i am new to facepager. I want to collect allowed individual's facebook posts for my thesis purpose. I have followed all the steps as described. But when try to log in facebook, it shows success but don't provide access token.
NB: I am using the (Facepager_Setup_4_2_22.windows.exe ) latest version
I have tried graph.facebook.com/v3.2 (default) and graph.facebook.com/v8.0[change from this file
Facebook.oa3.json all v3.2 to v8.0 ]
My OS windows10 updated version, not genuine

![Facepager](https://user-images.githubusercontent.com/69380371/89713393-47807700-d9b9-11ea-914e-eb556efd2dbe.JPG)

**Comment by strohne** [comment] 2020-08-08 22:12
Thanks for your bug report. Other users occasionally reported similar behavior but I could not reproduce the issue yet. 

So you see a red success message in the login window?

**Comment by Talha1721** [comment] 2020-08-09 01:07
Thank you for the reply.Yes I have seen this red success window. But I have created an app and got an access token. Using that token now I try to fetch data  but there is another error. Here is the screenshot-

![Facepager0](https://user-images.githubusercontent.com/69380371/89722735-f602d700-da0e-11ea-88fe-86494afc8356.JPG)

**Comment by strohne** [comment] 2020-08-09 07:30
Hi! Registering your own app is a good workaround if you go through app review. Otherwise access to public content is limited as you can see in the error message.  You can try: add app settings to Facepager (settings button) and if you are the admin of a page add that page ID in order to get data of the page.  Then login. Maybe change base path back to v3.2 as in the presets. 

Regarding the red success error case: are there any logs in the Facepager folder (under your user folder)?

**Comment by strohne** [comment] 2020-12-05 00:55
Hi, you had login problems, right? Could you please try whether the latest version (pre-release) works?

**Comment by jobdiogenes** [comment] 2021-01-03 19:19
I get the same login problem. 
First I try to login then show "need an ID",  then I put in setttings my fb id. click again. open a window (login) and say "invalid App ID". Then now I understood why registering your own app id works. I using FacePager 4.3,

**Comment by strohne** [comment] 2021-01-03 21:27
Hi @jobdiogenes , can you post a screenshot of the  "need an ID"-message? I'm not sure whether I understand where this comes from.

**Comment by jobdiogenes** [comment] 2021-01-05 02:18
> Hi @jobdiogenes , can you post a screenshot of the "need an ID"-message? I'm not sure whether I understand where this comes from.

![image](https://user-images.githubusercontent.com/1182381/103599142-2cbc1b00-4ee3-11eb-8360-8131855735aa.png)

**Comment by strohne** [comment] 2021-01-09 18:04
Are you on Linux, Mac, or Windows? With Linux, you need to register your own app at Facebook or whatever API provider you want to use. Then you enter the client ID into the settings.

**Comment by aymen-ch** [comment] 2021-01-14 14:48
I tried to collect the data with the source code, but I had a problem I'm not registered at facepager

**Comment by strohne** [comment] 2021-01-14 15:53
Hi! If you want to use it from source, you need to register your own app at Facebook and provide the client id. See https://github.com/strohne/Facepager/blob/master/src/credentials.py.readme

I close the issue since this is not related to developing Facepager but rather about using Facepager. If you have more questions, try out the Facepager user group on FAcebook :)

**Closed by strohne** 2021-01-14 15:53 UTC

**Comment by strohne** [comment] 2021-02-01 22:51
Found the error and hopefully fixed it. Credits go to a very helpful user at the #SMARTDatasprint 2021. Try out the new version.
